version: 2
updates:
  - package-ecosystem: "pip" # See documentation for possible values
    directories:
      - "/packages/typespec-python/test/azure/"
      - "/packages/typespec-python/test/unbranded/"
    schedule:
      interval: "weekly"
    # Include a list of updated dependencies
    # with a prefix determined by the dependency group
    commit-message:
      prefix: "pip prod"
      prefix-development: "pip dev"
      include: "scope"
