emit:
  - "@azure-tools/typespec-autorest"
options:
  "@azure-tools/typespec-autorest":
    emitter-output-dir: "{project-root}/"
    output-file: "{azure-resource-provider-folder}/{service-name}/{version-status}/{version}/contentsafety.json"
    azure-resource-provider-folder: "data-plane"
    examples-directory: ./examples
