name: autrest.python - http-client-python - ci

trigger:
  branches:
    exclude:
      - '*'

pr:
  branches:
    exclude:
      - '*'

schedules:
  - cron: "0 0 * * *"
    displayName: Daily midnight run
    branches:
      include:
        - main
    always: true

pool:
  name: "azsdk-pool-mms-ubuntu-2004-general"
  vmImage: "MMSUbuntu20.04"

variables:
  - group: Azure SDK Auto Release Pipeline Secrets

jobs:
- job: CreatePrForHttpClientPython

  steps:
  - task: NodeTool@0
    displayName: 'Install Node.js 20.x'
    inputs:
      versionSpec: '20.x'

  - task: UsePythonVersion@0
    displayName: "Use Python 3.10"
    inputs:
        versionSpec: 3.10

  - script: npm install -g pnpm@9.5.0
    displayName: Install pnpm 9.5.0

  - script: npm install -g autorest
    displayName: Install autorest

  - bash: |
        YmlPath=$(pwd)
        echo "##vso[task.setvariable variable=YmlPath]$YmlPath"
    displayName: find yml path

  - bash: |
      git config --global user.email "AutoPrFromHttpClientPython"
      git config --global user.name "AutoPrFromHttpClientPython"
      mkdir $(Build.SourcesDirectory)/typespec
      git clone https://github.com/microsoft/typespec.git $(Build.SourcesDirectory)/typespec

      mkdir $(Build.SourcesDirectory)/autorest.python
      git clone https://Azure:$(Yuchao-GitToken)@github.com/Azure/autorest.python.git $(Build.SourcesDirectory)/autorest.python
    displayName: clone repo

  - bash: |
      pip install -r $(YmlPath)/auto-pr-from-http-client-python.txt
      PULL_URL_PARAM=""
      if [ -n "$PULL_REQUEST_URL" ]; then
        PULL_URL_PARAM="--pull-url=$PULL_REQUEST_URL"
        echo "Pull Request URL: $PULL_REQUEST_URL"
      else
        echo "No Pull Request URL provided. Will sync from main branch."
      fi
      ARTIFACTS_PARAM=""
      if [ -n "$ARTIFACTS_URL" ]; then
        ARTIFACTS_PARAM="--artifacts-url=$ARTIFACTS_URL"
        echo "Artifacts URL: $ARTIFACTS_URL"
      else
        echo "No Artifacts URL provided."
      fi
      PIPELINE_LINK="$(System.TeamFoundationCollectionUri)$(System.TeamProject)/_build/results?buildId=$(Build.BuildId)"
      echo "Pipeline Link: $PIPELINE_LINK"
      python $(YmlPath)/auto-pr-from-http-client-python.py \
        $PULL_URL_PARAM \
        --repo-token=$(Yuchao-GitToken) \
        --typespec-repo-path=$(Build.SourcesDirectory)/typespec \
        $ARTIFACTS_PARAM \
        --ado-token=$(PIPELINE-TOKEN) \
        --pipeline-link="$PIPELINE_LINK"
    workingDirectory: $(Build.SourcesDirectory)/autorest.python
    displayName: create PR
