name: autrest.python - http-client-python - ci

trigger:
  branches:
    exclude:
      - '*'

pr:
  branches:
    exclude:
      - '*'

pool:
  name: "azsdk-pool-mms-ubuntu-2004-general"
  vmImage: "MMSUbuntu20.04"

variables:
  - name: HttpClientPythonBranch
    value: "main"

# variables:
#   - group: Release Secrets for GitHub

resources:
  repositories:
    # - repository: azure-sdk-for-python
    #   type: github
    #   name: Azure/azure-sdk-for-python
    #   endpoint: azure
    #   ref: main
    - repository: typespec
      type: github
      name: microsoft/typespec
      endpoint: microsoft
      ref: ${{ parameters.HttpClientPythonBranch }}

jobs:
- job: BuildAndCreatePr

  steps:
  # build and publish package for http-client-python
  - checkout: typespec

  - task: NodeTool@0
    displayName: 'Install Node.js 18.x'
    inputs:
      versionSpec: '18.x'

  - script: npm install
    displayName: npm install http-client-python
    workingDirectory: $(Build.SourcesDirectory)/typespec/packages/http-client-python

  - script: npm run build
    displayName: npm build http-client-python
    workingDirectory: $(Build.SourcesDirectory)/typespec/packages/http-client-python

  - script: npm pack
    displayName: npm pack http-client-python
    workingDirectory: $(Build.SourcesDirectory)/typespec/packages/http-client-python
  
  - bash: |
      AbsolutePkgPath=$(find "$(pwd)" -name "typespec-http-client-python-*" -maxdepth 1)
      echo "##vso[task.setvariable variable=AbsolutePkgPath;isOutput=true]$(AbsolutePkgPath)"
    workingDirectory: $(Build.SourcesDirectory)/typespec/packages/http-client-python

  - publish: $(AbsolutePkgPath)
    artifact: http-client-python





  - script: npm install -g pnpm@9.5.0
    displayName: Install pnpm 9.5.0
