name: autrest.python - http-client-python - ci

trigger:
  branches:
    exclude:
      - '*'

pr:
  branches:
    exclude:
      - '*'

pool:
  name: "azsdk-pool-mms-ubuntu-2004-general"
  vmImage: "MMSUbuntu20.04"

variables:
  - group: Azure SDK Auto Release Pipeline Secrets

jobs:
- job: CreatePrForHttpClientPython

  steps:
  - task: NodeTool@0
    displayName: 'Install Node.js 18.x'
    inputs:
      versionSpec: '18.x'

  - task: UsePythonVersion@0
    displayName: "Use Python 3.10"
    inputs:
        versionSpec: 3.10

  - script: npm install -g pnpm@9.5.0
    displayName: Install pnpm 9.5.0

  - script: npm install -g autorest
    displayName: Install autorest

  - bash: |
        YmlPath=$(pwd)/eng/pipelines
        echo "##vso[task.setvariable variable=YmlPath]$YmlPath"
    displayName: find yml path

  - bash: |
      git config --global user.email "AutoPrFromHttpClientPython"
      git config --global user.name "AutoPrFromHttpClientPython"
      mkdir $(Build.SourcesDirectory)/typespec
      git clone https://github.com/microsoft/typespec.git $(Build.SourcesDirectory)/typespec

      mkdir $(Build.SourcesDirectory)/autorest.python
      git clone https://Azure:$(Yuchao-GitToken)@github.com/Azure/autorest.python.git $(Build.SourcesDirectory)/autorest.python
    displayName: clone repo

  - bash: |
      pip install -r $(YmlPath)/auto-pr-from-http-client-python.txt
      python $(YmlPath)/auto-pr-from-http-client-python.py --pull-url=$(PULL-REQUEST-URL) --repo-token=$(Yuchao-GitToken) --typespec-repo-path=$(Build.SourcesDirectory)/typespec --artifacts-url=$(ARTIFACTS-URL)
    workingDirectory: $(Build.SourcesDirectory)/autorest.python
    displayName: create PR
