trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

resources:
  repositories:
    - repository: azure-sdk-tools
      type: github
      endpoint: Azure
      name: Azure/azure-sdk-tools

variables:
  PythonVersion: "3.7"
  AUTOREST_TESTSERVER_COVERAGE_DIRECTORY: "$(Build.SourcesDirectory)/autorest.python/packages/autorest.python/coverage/"
  PROXY_URL: http://localhost:5000
  PROXY_MANUAL_START: true

parameters:
  - name: VerificationPackages
    type: object
    default:
    - name: azure-storage-blob
      service: storage
    - name: azure-storage-queue
      service: storage
    - name: azure-storage-file-datalake
      service: storage
    - name: azure-storage-file-share
      service: storage
    - name: azure-ai-language-questionanswering
      service: cognitivelanguage

jobs:
  - job: "AutoRest_Python_CI"
    displayName: "Run AutoRest CI Checks"

    strategy:
      matrix:
        Windows_Python37:
          OSName: "Windows"
          OSVmImage: "MMS2019"
          PythonVersion: "3.7"
        Linux_Python37:
          OSName: "Linux"
          OSVmImage: "MMSUbuntu20.04"
          PythonVersion: "3.7"
        Linux_Python310:
          OSName: "Linux"
          OSVmImage: "MMSUbuntu20.04"
          PythonVersion: "3.10"
        Linux_Python311:
          OSName: "Linux"
          OSVmImage: "MMSUbuntu22.04"
          PythonVersion: "3.11"

    pool:
      name: azsdk-pool-mms-ubuntu-2004-general
      vmImage: $(OSVmImage)

    steps:
      - template: ci-template.yml
        parameters:
            installAutorest: true
            folderName: "autorest.python"
            pythonCodeChecks: false
            pythonFolderName: autorest
            regenerate: false

      - script: |
          pip install pip==20.2
          pip install tox==3.27.1 coverage
        displayName: "Install Env Specific Reqs in Target PyVersion $(PythonVersion)"
      - ${{ if eq(ne(variables['Build.Reason'], 'PullRequest'), 'True') }}:
          - script: |
              git clone https://github.com/Azure/azure-sdk-for-python.git --depth=1 --branch main
            displayName: "Clone python repo"
          - script: mv $(Build.SourcesDirectory)/azure-sdk-for-python/sdk .
            displayName: Move sdk folder up a level
            workingDirectory: "$(Build.SourcesDirectory)"

          - script: |
              pip install tox-monorepo
            displayName: "Prepare environment"
            workingDirectory: "$(Build.SourcesDirectory)"

          - ${{ each package in parameters.VerificationPackages }}:
              - script: |
                  autorest ./swagger/README.md --use=$(Build.SourcesDirectory)/autorest.python/packages/autorest.python --modelerfour.seal-single-value-enum-by-default
                displayName: "Regenerate target package ${{ package.name }}"
                workingDirectory: "$(Build.SourcesDirectory)/sdk/${{ package.service }}/${{ package.name }}"
              - script: |
                  tox -e whl -c ../../../eng/tox/tox.ini
                displayName: "Run tests for ${{ package.name }}"
                workingDirectory: "$(Build.SourcesDirectory)/sdk/${{ package.service }}/${{ package.name }}"
  - job: "Cadl_Python_CI"
    displayName: "Run Cadl Python CI Checks"

    strategy:
      matrix:
        Windows_Python37:
          OSName: "Windows"
          OSVmImage: "MMS2019"
          PythonVersion: "3.7"
        Linux_Python37:
          OSName: "Linux"
          OSVmImage: "MMSUbuntu20.04"
          PythonVersion: "3.7"
        Linux_Python310:
          OSName: "Linux"
          OSVmImage: "MMSUbuntu20.04"
          PythonVersion: "3.10"
        Linux_Python311:
          OSName: "Linux"
          OSVmImage: "MMSUbuntu22.04"
          PythonVersion: "3.11"

    pool:
      name: azsdk-pool-mms-ubuntu-2004-general
      vmImage: $(OSVmImage)

    steps:
      - template: ci-template.yml
        parameters:
            installCadl: true
            installCadlRanch: true
            folderName: "cadl-python"
            regenerate: true

      - script: |
          pip install pip==20.2
          pip install tox==3.27.1 coverage==4.5.4
        displayName: "Install Env Specific Reqs in Target PyVersion $(PythonVersion)"

      - template: generated-code-checks-template.yml
        parameters:
            package: "cadl-python"

      - script: cadl-ranch check-coverage http/
        displayName: Check Coverage
        workingDirectory: $(Build.SourcesDirectory)/autorest.python/packages/cadl-python/node_modules/@azure-tools/cadl-ranch-specs
        continueOnError: true

      - publish: $(Build.SourcesDirectory)/autorest.python/packages/cadl-python/node_modules/@azure-tools/cadl-ranch-specs/cadl-ranch-coverage.json
        artifact: CoverageReport
