trigger:
  branches:
    include:
      - autorestv3

pr:
  branches:
    include:
      - autorestv3

resources:
  repositories:
    - repository: azure-sdk-tools
      type: github
      endpoint: Azure
      name: Azure/azure-sdk-tools

variables:
  PythonVersion: "3.7"
  AUTOREST_TESTSERVER_COVERAGE_DIRECTORY: "$(Build.SourcesDirectory)/autorest.python/packages/autorest.python/coverage/"
  PROXY_URL: http://localhost:5000
  PROXY_MANUAL_START: true

parameters:
  - name: VerificationPackages
    type: object
    default:
    - name: azure-messaging-webpubsubservice
      service: webpubsub
    - name: azure-storage-blob
      service: storage
    - name: azure-storage-queue
      service: storage
    - name: azure-storage-file-datalake
      service: storage
    - name: azure-storage-file-share
      service: storage
    - name: azure-ai-language-questionanswering
      service: cognitivelanguage

jobs:
  - job: "AutoRest_Python_CI"
    displayName: "Run AutoRest CI Checks"

    trigger:
      paths:
        include:
        - packages/autorest.python/
        - ./

    strategy:
      matrix:
        Windows_Python37:
          OSName: "Windows"
          OSVmImage: "MMS2019"
          PythonVersion: "3.7"
        Linux_Python37:
          OSName: "Linux"
          OSVmImage: "MMSUbuntu20.04"
          PythonVersion: "3.7"
        Linux_Python310:
          OSName: "Linux"
          OSVmImage: "MMSUbuntu20.04"
          PythonVersion: "3.10"

    pool:
      name: azsdk-pool-mms-ubuntu-2004-general
      vmImage: $(OSVmImage)

    steps:
      - template: ci-template.yml
        parameters:
            installAutorest: true
            folderName: "autorest.python"
            pythonCodeChecks: true
            pythonFolderName: autorest
            regenerate: true

      - script: |
          pip install pip==20.2
          pip install tox coverage
        displayName: "Install Env Specific Reqs in Target PyVersion $(PythonVersion)"

      - script: tox -e ci
        displayName: 'Execute legacy "azure" Tests - Python $(PythonVersion)'
        workingDirectory: $(Build.SourcesDirectory)/autorest.python/packages/autorest.python/test/azure/legacy

      - script: tox -e ci
        displayName: 'Execute version-tolerant "azure" Tests - Python $(PythonVersion)'
        workingDirectory: $(Build.SourcesDirectory)/autorest.python/packages/autorest.python/test/azure/legacy

      - script: tox -e lint
        displayName: 'Lint version-tolerant "azure" Tests - Python $(PythonVersion)'
        condition: and(succeededOrFailed(), eq(variables['PythonVersion'], '3.7'))
        workingDirectory: $(Build.SourcesDirectory)/autorest.python/packages/autorest.python/test/azure/version-tolerant

      - script: tox -e mypy
        displayName: 'Mypy version-tolerant "azure" Tests - Python $(PythonVersion)'
        condition: and(succeededOrFailed(), eq(variables['PythonVersion'], '3.10'))
        workingDirectory: $(Build.SourcesDirectory)/autorest.python/packages/autorest.python/test/azure/version-tolerant

      - script: tox -e ci
        displayName: 'Execute legacy "vanilla" Tests - Python $(PythonVersion)'
        workingDirectory: $(Build.SourcesDirectory)/autorest.python/packages/autorest.python/test/vanilla/legacy

      - script: tox -e ci
        displayName: 'Execute version-tolerant "vanilla" Tests - Python $(PythonVersion)'
        workingDirectory: $(Build.SourcesDirectory)/autorest.python/packages/autorest.python/test/vanilla/version-tolerant

      - script: tox -e lint
        displayName: 'Lint version-tolerant "vanilla" Tests - Python $(PythonVersion)'
        condition: and(succeededOrFailed(), eq(variables['PythonVersion'], '3.7'))
        workingDirectory: $(Build.SourcesDirectory)/autorest.python/packages/autorest.python/test/vanilla/version-tolerant

      - script: tox -e mypy
        displayName: 'Mypy version-tolerant "vanilla" Tests - Python $(PythonVersion)'
        condition: and(succeededOrFailed(), eq(variables['PythonVersion'], '3.10'))
        workingDirectory: $(Build.SourcesDirectory)/autorest.python/packages/autorest.python/test/vanilla/version-tolerant

      - script: tox -e ci
        displayName: 'Execute version-tolerant update "dpg" Tests - Python $(PythonVersion)'
        workingDirectory: $(Build.SourcesDirectory)/autorest.python/packages/autorest.python/test/dpg/version-tolerant

      - script: tox -e lint
        displayName: 'Lint version-tolerant "dpg" Tests - Python $(PythonVersion)'
        condition: and(succeededOrFailed(), eq(variables['PythonVersion'], '3.7'))
        workingDirectory: $(Build.SourcesDirectory)/autorest.python/packages/autorest.python/test/dpg/version-tolerant

      - script: tox -e mypy
        displayName: 'Mypy version-tolerant "dpg" Tests - Python $(PythonVersion)'
        condition: and(succeededOrFailed(), eq(variables['PythonVersion'], '3.10'))
        workingDirectory: $(Build.SourcesDirectory)/autorest.python/packages/autorest.python/test/dpg/version-tolerant

      - script: tox -e ci
        displayName: 'Execute "multiapi" Tests - Python $(PythonVersion)'
        workingDirectory: $(Build.SourcesDirectory)/autorest.python/packages/autorest.python/test/multiapi

      - script: |
          npm run coverage -- publish --repo=$(Build.Repository.Name) --ref=$(Build.SourceBranch) --githubToken=$(github-token) --azStorageAccount=$(storage-coverage-user) --azStorageAccessKey=$(storage-coverage-pass) --coverageDirectory=$(AUTOREST_TESTSERVER_COVERAGE_DIRECTORY)
        workingDirectory: $(Build.SourcesDirectory)/autorest.python/packages/autorest.python/node_modules/@microsoft.azure/autorest.testserver
        displayName: "Publish coverage report to storage account"
        condition: and(succeededOrFailed(), eq(variables['PythonVersion'], '3.10'))

      - ${{ if eq(ne(variables['Build.Reason'], 'PullRequest'), 'True') }}:
          - script: |
              git clone https://github.com/Azure/azure-sdk-for-python.git --depth=1 --branch main $(Build.SourcesDirectory)/regenerated/
            displayName: "Clone python repo"

          - script: |
              pip install tox-monorepo
            displayName: "Prepare environment"
            workingDirectory: "$(Build.SourcesDirectory)/regenerated/"

          - ${{ each package in parameters.VerificationPackages }}:
              - script: |
                  autorest ./swagger/README.md --use=$(Build.SourcesDirectory)/autorest.python/packages/autorest.python --modelerfour.seal-single-value-enum-by-default
                displayName: "Regenerate target package ${{ package.name }}"
                workingDirectory: "$(Build.SourcesDirectory)/regenerated/sdk/${{ package.service }}/${{ package.name }}"
              - script: |
                  tox -e whl -c ../../../eng/tox/tox.ini
                displayName: "Run tests for ${{ package.name }}"
                workingDirectory: "$(Build.SourcesDirectory)/regenerated/sdk/${{ package.service }}/${{ package.name }}"
  - job: "Cadl_Python_CI"
    displayName: "Run Cadl Python CI Checks"

    trigger:
      paths:
        include:
        - packages/cadl-python/
        - ./

    strategy:
      matrix:
        Windows_Python37:
          OSName: "Windows"
          OSVmImage: "MMS2019"
          PythonVersion: "3.7"
        Linux_Python37:
          OSName: "Linux"
          OSVmImage: "MMSUbuntu20.04"
          PythonVersion: "3.7"
        Linux_Python310:
          OSName: "Linux"
          OSVmImage: "MMSUbuntu20.04"
          PythonVersion: "3.10"

    pool:
      name: azsdk-pool-mms-ubuntu-2004-general
      vmImage: $(OSVmImage)

    steps:
      - template: ci-template.yml
        parameters:
            installCadl: true
            installCadlRanch: true
            folderName: "cadl-python"
            regenerate: true

      - script: tox -e ci
        displayName: 'Execute Mock API tests - Python $(PythonVersion)'
        workingDirectory: $(Build.SourcesDirectory)/autorest.python/packages/cadl-python/test/mock_api_tests

      - script: cadl-ranch check-coverage http/
        displayName: Check Coverage
        workingDirectory: $(Build.SourcesDirectory)/autorest.python/packages/cadl-python/node_modules/@azure-tools/cadl-ranch-specs
        continueOnError: true

      - publish: $(Build.SourcesDirectory)/autorest.python/packages/cadl-python/node_modules/@azure-tools/cadl-ranch-specs/cadl-ranch-coverage-python.json
        artifact: CoverageReport
