trigger:
  branches:
    include:
      - main
pr: none

resources:
  repositories:
    - repository: azure-sdk-tools
      type: github
      endpoint: Azure
      name: Azure/azure-sdk-tools

variables:
  PythonVersion: "3.10"

steps:
    - template: ci-template.yml
      parameters:
          installTypeSpec: true
          installCadlRanch: true
          folderName: "typespec-python"
          regenerate: true

    - script: |
            tox run -e ci
      displayName: Mock Api Tests for Unbranded
      workingDirectory: $(Build.SourcesDirectory)/autorest.python/packages/typespec-python/test/unbranded

    - task: AzureCLI@2
      displayName: Upload scenario manifest for unbranded
      inputs:
        azureSubscription: "TypeSpec Storage"
        scriptType: "bash"
        scriptLocation: "inlineScript"
        inlineScript: npx tsp-spector upload-coverage --coverageFile ./spec-coverage.json --generatorName "@typespec/http-client-python" --storageAccountName typespec --generatorVersion $(node -p -e "require('$(Build.SourcesDirectory)/autorest.python/packages/typespec-python/node_modules/@typespec/http-client-python/package.json').version") --containerName coverages --generatorMode standard
        workingDirectory: $(Build.SourcesDirectory)/autorest.python/packages/typespec-python/node_modules/@azure-tools/azure-http-specs

    - script: |
            tox run -e ci
      displayName: Mock Api Tests for Azure
      workingDirectory: $(Build.SourcesDirectory)/autorest.python/packages/typespec-python/test/azure

    - task: AzureCLI@2
      displayName: Upload scenario manifest for azure
      inputs:
        azureSubscription: "TypeSpec Storage"
        scriptType: "bash"
        scriptLocation: "inlineScript"
        inlineScript: npx tsp-spector upload-coverage --coverageFile ./spec-coverage.json --generatorName "@azure-tools/typespec-python" --storageAccountName typespec --generatorVersion $(node -p -e "require('$(Build.SourcesDirectory)/autorest.python/packages/typespec-python/package.json').version") --containerName coverages --generatorMode azure
        workingDirectory: $(Build.SourcesDirectory)/autorest.python/packages/typespec-python/node_modules/@azure-tools/azure-http-specs
