# This is a manual pipeline, don't trigger automatically
trigger: none
pr: none

pool:
    vmImage: "ubuntu-latest"

variables:
    NodeVersion: "14.x"
    AutorestTestFolder: "$(Build.SourcesDirectory)/packages/autorest.python/test/"

steps:
    - script: npm install -g pnpm
      displayName: Install PNPM

    - script: pnpm install
      displayName: Install dependencies

    - script: pnpm run build
      displayName: Build

    - script: |
          npm pack
          AbsolutePkgPath=$(find "$(pwd)" -name "autorest-python-*" -maxdepth 1)
          cd ../..
          echo $AbsolutePkgPath
          npm install $AbsolutePkgPath --loglevel verbose
      displayName: Test Autorest tarball
      workingDirectory: $(Build.SourcesDirectory)/packages/autorest.python/

    - script: |
          npm pack
          AbsolutePkgPath=$(find "$(pwd)" -name "autorest-python-*" -maxdepth 1)
          cd ../..
          npm install $AbsolutePkgPath
      displayName: Test Cadl tarball
      workingDirectory: $(Build.SourcesDirectory)/packages/cadl-python/

    - script: |
          pnpm config set //registry.npmjs.org/:_authToken=$(azure-sdk-npm-token)
          NPM_AUTH_TOKEN="$(azure-sdk-npm-token)" pnpm -r publish --access public --no-git-checks
      displayName: Publish packages
