# This is a manual pipeline, don't trigger automatically
trigger: none
pr: none

pool:
    vmImage: "ubuntu-latest"

variables:
    NodeVersion: "14.x"
    AutorestTestFolder: "$(Build.SourcesDirectory)/packages/autorest.python/test/"

steps:
    - script: |
        npm install -g pnpm
        pnpm --version
      displayName: Install PNPM

    - script: npm install -g @azure-tools/cadl-ranch
      displayName: Install cadl ranch

    - script: pnpm install
      displayName: Install dependencies

    - script: pnpm run build
      displayName: Build

    - script: |
          pnpm config set //registry.npmjs.org/:_authToken=$(azure-sdk-npm-token)
          pnpm -r publish --access public --no-git-checks
      displayName: Publish packages
    - publish: /home/vsts/.npm/_logs
      artifact: NPMLogs
