# This is a manual pipeline, don't trigger automatically
trigger: none
pr: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  NodeVersion: '14.x'
  TestFolder: '$(Build.SourcesDirectory)/packages/autorest.python/test/'
  AUTOREST_TESTSERVER_COVERAGE_DIRECTORY: "$(Build.SourcesDirectory)/packages/autorest.python/coverage/"

steps:
  - task: NodeTool@0
    displayName: 'Install Node.js $(NodeVersion)'
    inputs:
      versionSpec: '$(NodeVersion)'

  - task: UsePythonVersion@0
    displayName: 'Use Python 3.7'
    inputs:
      versionSpec: 3.7

  - script: |
      npm install -g pnpm
      npm install -g autorest
      pnpm install
      pip install -r dev_requirements.txt
    displayName: "Prepare Environment for Generation"
    workingDirectory: $(Build.SourcesDirectory)/packages/autorest.python/

  - script: |
      pylint autorest
    displayName: 'Pylint'
    workingDirectory: $(Build.SourcesDirectory)/packages/autorest.python/

  - script: |
      mypy autorest
    displayName: 'Mypy'
    workingDirectory: $(Build.SourcesDirectory)/packages/autorest.python/

  - script: |
      pytest test/unittests
    displayName: 'Unit tests'
    workingDirectory: $(Build.SourcesDirectory)/packages/autorest.python/

  - script: |
      pip install tox coverage==4.5.4
    displayName: 'Install Env Specific Reqs in Target PyVersion $(PythonVersion)'

  - script: |
      cd $(TestFolder)/azure/legacy
      tox -e ci
    displayName: 'Execute legacy "azure" Tests - Python $(PythonVersion)'
    workingDirectory: $(Build.SourcesDirectory)/packages/autorest.python/

  - script: |
      cd $(TestFolder)/azure/version-tolerant
      tox -e ci
    displayName: 'Execute version tolerant "azure" Tests - Python $(PythonVersion)'
    workingDirectory: $(Build.SourcesDirectory)/packages/autorest.python/

  - script: |
      cd $(TestFolder)/vanilla/legacy
      tox -e ci
    displayName: 'Execute legacy "vanilla" Tests - Python $(PythonVersion)'
    workingDirectory: $(Build.SourcesDirectory)/packages/autorest.python/

  - script: |
      cd $(TestFolder)/vanilla/version-tolerant
      tox -e ci
    displayName: 'Execute version tolerant "vanilla" Tests - Python $(PythonVersion)'
    workingDirectory: $(Build.SourcesDirectory)/packages/autorest.python/

  - script: |
      cd $(TestFolder)/dpg/version-tolerant
      tox -e ci
    displayName: 'Execute version tolerant "dpg" Tests - Python $(PythonVersion)'
    workingDirectory: $(Build.SourcesDirectory)/packages/autorest.python/

  - script: |
      export RELEASE_VERSION=$(node -p -e "require('./package.json').version")
      npm pack
      npx publish-release --token $(azuresdk-github-pat) --repo autorest.python --owner azure --name "Autorest for Python v$RELEASE_VERSION" --tag v$RELEASE_VERSION --notes='Release version of Autorest for Python v5' --prerelease --editRelease false --assets autorest-python-$RELEASE_VERSION.tgz --target_commitish $(Build.SourceBranchName)
    displayName: 'Publish GitHub release'
    workingDirectory: $(Build.SourcesDirectory)/packages/autorest.python/

  - script: |
      echo "//registry.npmjs.org/:_authToken=$(azure-sdk-npm-token)" > ./.npmrc
      npm publish --access public
    displayName: 'Publish to npm'
    workingDirectory: $(Build.SourcesDirectory)/packages/autorest.python/
