# This is a manual pipeline, don't trigger automatically
trigger: none
pr: none

extends: 
  template: /eng/pipelines/templates/stages/1es-redirect.yml
  parameters:
    stages: 
      - stage: Release

        variables:
          - template: /eng/pipelines/templates/variables/image.yml

        jobs:
          - job: Release
            pool:
                name: $(LINUXPOOL)
                image: $(LINUXVMIMAGE)
                os: linux

            variables:
                NodeVersion: "20.x"
                AutorestTestFolder: "$(Build.SourcesDirectory)/packages/autorest.python/test/"

            steps:
                - task: UsePythonVersion@0
                  displayName: "Use Python 3.10"
                  inputs:
                      versionSpec: 3.10

                - script: npm install -g pnpm@9.5.0
                  displayName: Install PNPM 9.5.0

                - script: pnpm install
                  displayName: Install dependencies

                - script: pnpm run build
                  displayName: Build

                - script: pip install -r dev_requirements.txt
                  displayName: Install Autorest Python dev requirements
                  workingDirectory: $(Build.SourcesDirectory)/packages/autorest.python/

                - script: pip install -r dev_requirements.txt
                  displayName: Install Cadl dev requirements
                  workingDirectory: $(Build.SourcesDirectory)/packages/typespec-python/

                - script: |
                      cd $(AutorestTestFolder)/azure/version-tolerant
                      tox run -e ci
                  displayName: Execute Autorest Azure Version Tolerant Tests
                  workingDirectory: $(Build.SourcesDirectory)/packages/autorest.python/
                - script: |
                      cd $(AutorestTestFolder)/vanilla/version-tolerant
                      tox run -e ci
                  displayName: Execute Autorest Vanilla Version Tolerant Tests
                  workingDirectory: $(Build.SourcesDirectory)/packages/autorest.python/
                - script: |
                      cd $(AutorestTestFolder)/dpg/version-tolerant
                      tox run -e ci
                  displayName: Execute Autorest DPG Version Tolerant Tests
                  workingDirectory: $(Build.SourcesDirectory)/packages/autorest.python/
                - script: |
                      cd test/azure
                      tox run -e ci
                  displayName: Execute Typespec Azure Tests
                  workingDirectory: $(Build.SourcesDirectory)/packages/typespec-python/
                - script: |
                      cd test/unbranded
                      tox run -e ci
                  displayName: Execute Typespec Unbranded Tests
                  workingDirectory: $(Build.SourcesDirectory)/packages/typespec-python/

                - script: |
                      pnpm config set //registry.npmjs.org/:_authToken=$(azure-sdk-npm-token)
                      pnpm -r publish --access public --no-git-checks
                  displayName: Publish packages
