trigger:
  branches:
    include:
      - main

schedules:
- cron: '0 0 * * *'
  displayName: Daily midnight build to regenerate SDK
  branches:
    include:
    - main

pr: none

pool:
  name: "azsdk-pool-mms-ubuntu-2004-general"
  vmImage: "MMSUbuntu20.04"

variables:
  group: Release Secrets for GitHub
  NodeVersion: "20.x"
  PythonVersion: "3.10"


resources:
  repositories:
    - repository: azure-sdk-for-python
      type: github
      name: Azure/azure-sdk-for-python
      endpoint: azure
      ref: main

jobs:
- job: Generate_SDK

  timeoutInMinutes: 120

  steps:
  - checkout: self
    fetchDepth: 1
  - checkout: azure-sdk-for-python

  - task: NodeTool@0
    displayName: 'Install Node.js $(NodeVersion)'
    inputs:
      versionSpec: '$(NodeVersion)'

  - script: npm install -g pnpm@8.3.1
    displayName: Install pnpm 8.3.1

  - script: pnpm install
    displayName: pnpm install
    workingDirectory: $(Build.SourcesDirectory)/autorest.python

  - script: pnpm build
    displayName: pnpm build
    workingDirectory: $(Build.SourcesDirectory)/autorest.python
 
  - script: npm pack
    displayName: npm pack
    workingDirectory: $(Build.SourcesDirectory)/autorest.python/packages/typespec-python

  - script: npm install -g @azure-tools/typespec-client-generator-cli
    displayName: 'Install tsp-client'

  - script: |
      python3 $(Build.SourcesDirectory)/autorest.python/eng/scripts/sdk_regenerate.py --sdk-root=$(Build.SourcesDirectory)/azure-sdk-for-python --typespec-python-root=$(Build.SourcesDirectory)/autorest.python --typespec-python-branch=$(Build.SourceBranchName)
    displayName: 'Generate SDK'
    workingDirectory: $(Build.SourcesDirectory)/azure-sdk-for-python

  - template: /eng/common/pipelines/templates/steps/git-push-changes.yml
    parameters:
      WorkingDirectory: $(Build.SourcesDirectory)/azure-sdk-for-python
      ScriptDirectory: $(Build.SourcesDirectory)/azure-sdk-for-python/eng/common/scripts
      BaseRepoBranch: typespec-python-$(Build.SourceBranchName)
      TargetRepoName: azure-sdk-for-python
      CommitMsg: 'Regenerate SDK based on typespec-python branch `$(Build.SourceBranchName)`'
      PushArgs: '--force'

  - ${{ if ne(variables['Build.SourceBranchName'], 'main') }}:
    - task: PowerShell@2
      displayName: Create pull request
      condition: and(succeeded(), eq(variables['HasChanges'], 'true'))
      inputs:
        pwsh: true
        WorkingDirectory: $(Build.SourcesDirectory)/azure-sdk-for-python
        filePath:  $(Build.SourcesDirectory)/azure-sdk-for-python/eng/common/scripts
        arguments: >
          -RepoOwner "Azure"
          -RepoName "azure-sdk-for-python"
          -BaseBranch "refs/heads/main"
          -PROwner "azure-sdk"
          -PRBranch "typespec-python-$(Build.SourceBranchName)"
          -AuthToken "$(azuresdk-github-pat)"
          -PRTitle "[Automation] Regenerate SDK based on typespec-python branch `$(Build.SourceBranchName)`"
          -OpenAsDraft "true"
