trigger:
  branches:
    include:
      - main
pr: none

pool:
  name: "azsdk-pool-mms-ubuntu-2004-general"
  vmImage: "MMSUbuntu20.04"

variables:
  group: Release Secrets for GitHub
  NodeVersion: "18.x"
  PythonVersion: "3.10"


resources:
  repositories:
    - repository: azure-sdk-for-python
      type: github
      endpoint: Azure
      name: Azure/azure-sdk-for-python

jobs:
- job: Generate_SDK

  timeoutInMinutes: 120

  steps:
  - checkout: self
    fetchDepth: 1
  - checkout: azure-sdk-for-python

  - task: NodeTool@0
    displayName: 'Install Node.js $(NodeVersion)'
    inputs:
      versionSpec: '$(NodeVersion)'

  - task: PowerShell@2
    displayName: 'Build typespec-python'
    inputs:
      pwsh: true
      filePath: $(Build.SourcesDirectory)/autorest.java/eng/scripts/Build-Packages.ps1
      workingDirectory: $(Build.SourcesDirectory)/autorest.python
      
  - script: npm install -g @azure-tools/typespec-client-generator-cli
    displayName: 'Install tsp-client'

