known_primary_types_mapping = {
    "none": "",
    "object": "object",
    "int": "int",
    "number": "float",
    "integer": "int",
    "long": "long",
    "double": "float",
    "decimal": "decimal.Decimal",
    "string": "str",
    "stream": "Generator",
    "bytearray": "bytearray",
    "date": "datetime.datetime",
    "date-time": "datetime.datetime",
    "datetimerfc1123": "datetime.datetime",
    "timespan": "timedelta",
    "boolean": "bool",
    "uuid": "str",
    "base64url": "bytes",
    "unixtime": "datetime.datetime",
    "duration": "datetime.timedelta",
}