name: Consistency

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  merge_group:
  workflow_dispatch: {}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check-changes:
    name: Check Changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 ## Needed for Changesets to find `main` branch
          submodules: recursive

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - run: git pull --force --no-tags origin main:main
        name: Get main ref

      - run: pnpm install
        name: Install dependencies

      - run: pnpm change verify
        name: Check changelog
        if: ${{ !startsWith(github.head_ref, 'publish/') && !startsWith(github.head_ref, 'dependabot/') && !startsWith(github.head_ref, 'backmerge/') && !startsWith(github.head_ref, 'auto-microsoft-') }}

      - run: pnpm check-version-mismatch
        name: Check version mismatch

      - run: pnpm lint
        name: Lint project

      - run: pnpm check-format
        name: Check formatting
