name: Prepare Auto Release Branch

# Disable as MS Org doesn't allow github action to create PR anymore. Can be re-added if a solution is found.
on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  pull-requests: write
  contents: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.x

      - run: npm install -g pnpm@7.27.1
        name: Install PNPM

      - run: pnpm install
        name: Install dependencies

      - name: Create release branch
        run: node ./eng/publish.mjs
